### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by teafff** [B1ACK917/2021HWAutoGrader#1]
Java的能用吗

**Comment by doraneko6** [comment]
更新了，应该可以了，请仔细阅读README并使用。

**Comment by teafff** [comment]
AutoGrader Running with args: ['java', '', '', '', '/usr/bin/java', '/home/wy/SDK_java/code/CodeCraft-2021/bin/com/huawei/java/main/Main.class', ['/home/wy/training-1.txt', '/home/wy/training-2.txt']]
  0%|             | 0/2 [00:00<?, ?it/s]"/usr/bin/java" "/home/wy/SDK_java/code/CodeCraft-2021/bin/com/huawei/java/main/Main.class"<"/home/wy/training-1.txt"
错误: 找不到或无法加载主类 .home.wy.SDK_java.code.CodeCraft-2021.bin.com.huawei.java.main.Main.class
/home/wy/.local/lib/python3.5/site-packages/matplotlib/font_manager.py:1241: UserWarning: findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
  (prop.get_family(), self.defaultFamily[fontext]))
  0%|             | 0/2 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "autograder.py", line 241, in <module>
    _ = grader(testCmd, d)
  File "autograder.py", line 207, in grader
    emptyRate), sum(energyCost) / len(energyCost), folderName, migTot, bombInfo
ZeroDivisionError: division by zero

报了这个错是为啥呢，我用which java查看了java路径就是/usr/bin/java

**Comment by B1ACK917** [comment]
感觉应该是java classpath的问题，我尝试修复了一下，感觉可以用了，如果还不行的话可以加我qq397615103细说。
推荐在Windows下运行，Linux在绘图时的字体和网页可能会有一些问题。

**Comment by teafff** [comment]
好的 我再试试

**Comment by teafff** [comment]
还是不行，能给我一个java示例的config.json吗  感觉我可能是路径问题

**Comment by doraneko6** [comment]
最新版本修改了java相关的逻辑，新版config应该不会出现classpath相关的问题了，此issue关闭，如有疑问欢迎再次开启该issue，谢谢。
