### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by Yjh-Rking** [B1ACK917/2021HWAutoGrader#3]
Traceback (most recent call last):
  File "autograder.py", line 244, in <module>
    _ = grader(testCmd, d)
  File "autograder.py", line 208, in grader
    emptyRate), sum(energyCost) / len(energyCost), folderName, migTot, bombInfo

这是啥原因..

**Comment by doraneko6** [comment]
这种情况通常是分析器没有获得到程序的输出或者输出格式不合法导致了数据为空，请检查你的程序是否使用标准输入输出以及输出格式是否正确，谢谢。

**Comment by Yjh-Rking** [comment]
用的同一份代码.官网能过跑了13e
然后这个就报错了... :(

**Comment by doraneko6** [comment]
请问你用的语言是java吗，java的话目前还有一些bug，我可能今天会尝试修复一下。如果是python和c++的话能把config复制到issue里给我看一下吗。

**Comment by Yjh-Rking** [comment]
{
  "language": "python",
  "pythonInterpreter": "",
  "executable": "",
  "sourceCode": "./CodeCraft-2021.py",
  "javaPath": "",
  "javaClass": "",
  "ioData": ["./data/training-1.txt", "./data/training-2.txt"]
}

代码文件和训练集都放在autograder.py同一个目录下了

谢谢

**Comment by B1ACK917** [comment]
感觉config好像没问题，能麻烦加我qq397615103一下吗，issue不太方便及时回复。

**Comment by doraneko6** [comment]
Bug已修复，Issue关闭。
