### ISSUE TITLE
运行出错，链表下标越界

### ISSUE THREAD

**Issue by zhongxuebin** [B1ACK917/2021HWAutoGrader#4]
AutoGrader Running with args: ['java', '', '', '', '', 'E:/test/java_SDK/bin/CodeCraft-2021.jar', ['E:/training-1.txt', 'E:/training-2.txt']]
  0%|             | 0/2 [00:15<?, ?it/s]
Traceback (most recent call last):
  File "autograder.py", line 256, in <module>
    _ = grader(testCmd, d)
  File "autograder.py", line 136, in grader
    dayServerInfo[day['request'][opInd][0]].append(op[1])
IndexError: list index out of range

**Comment by doraneko6** [comment]
应该是在某些情况下换行符导致的bug，我已经尝试修复了一下并更新。
