### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by Edward6316** [B1ACK917/2021HWAutoGrader#5]
返回错误；
错误如下：
dayServerInfo[day['request'][opInd][0]].append(op[1])
IndexError: list index out of range

**Comment by doraneko6** [comment]
应该是某些情况下换行符导致的bug，已推送更新。
由于存在同类issue：Duplicate of #4。此issue暂时关闭，如果有疑问，欢迎在#4下回复或者重开此issue。
