### ISSUE TITLE
运行出错，遇到除0的BUG

### ISSUE THREAD

**Issue by Kimxiaogen** [B1ACK917/2021HWAutoGrader#8]
今天down下来的代码，运行遇到如下异常：
![image](https://user-images.githubusercontent.com/26002010/111597357-08e15380-8809-11eb-938e-b6839e5c9324.png)

**Comment by doraneko6** [comment]
buildJARPath字段需要填写到jar文件所在的位置而不是bin文件夹所在的位置，请在后面加上\\CodeCraft-2021.jar
